const ActionTypes = {
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  FETCH_PROJECT: 'FETCH_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  NEW_PROJECT: 'NEW_PROJECT',
  AUTH_USER: 'AUTH_USER',
  DEAUTH_USER: 'DEAUTH_USER',
  AUTH_ERROR: 'AUTH_ERROR',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
};

export default ActionTypes;
