const ActionTypes = {
  FETCH_PROJECTS: 'FETCH_PROJECTS',
  FETCH_PROJECTS_FOR_USER: 'FETCH_PROJECTS_FOR_USER',
  FETCH_PROJECT: 'FETCH_PROJECT',
  DELETE_PROJECT: 'DELETE_PROJECT',
  NEW_PROJECT: 'NEW_PROJECT',
  AUTH_USER: 'AUTH_USER',
  DEAUTH_USER: 'DEAUTH_USER',
  TOGGLE_SIDEBAR: 'TOGGLE_SIDEBAR',
  TOGGLE_MODAL_VISIBILITY: 'TOGGLE_MODAL_VISIBILITY',
};

export default ActionTypes;
